### ISSUE TITLE
FTDI drivers and Codebender plugin not working to run from Browser

### ISSUE THREAD

**Issue by julesmoretti** [sparkfun/RedBot#16]
Hello there:

I have finished building the kit and am now at the following stage:
https://learn.sparkfun.com/tutorials/assembly-guide-for-redbot-with-shadow-chassis/10-run-it

I have a MacBook Pro retina and believe to have installed both the FTDI drivers and Codebender plugin.

At the very least the Codebender as it is listed in my chrome extensions as active.

The issue that I am facing is that within the "Test Some Code" section, I am unable to detect any other ports but:

```
/dev/cu.Bluetooth-Incoming-Port
/dev/cu.Bluetooth-Modem
```
So how can I troubleshoot this in order for me to be able to select COM42 as instructed in the tutorial?

Thank you for your help.

Jules

**Comment by ToniCorinne** [comment]
Make sure you are powering the RedBot. If there's no power to the board, it won't show up in your available ports. 

Double check you've completed these steps. If you aren't sure on these, reread the assembly guide and check out the images for additional help:
1) To program the RedBot from your browser, make sure you have the FTDI drivers and Codebender plugin) installed. Plug in the RedBot using a USB mini cable.
2) Turn the RedBot POWER switch to ON and the MOTOR switch to RUN.

**Comment by ToniCorinne** [comment]
Also, your COM port will not necessarily be COM42. That number is assigned based on how many serial devices have been plugged in before. Check out our [terminal basics tutorial](https://learn.sparkfun.com/tutorials/terminal-basics/connecting-to-your-device) if you need additional help with this.

**Comment by sean808080** [comment]
I'm having a similar problem in that the usbmodem port shows up.  The Arduino IDE works with it just fine.  The port when selected in the codebender test screen results in an error when attempting to load a test sketch:  

Could not connect to your device. Make sure that you have connected it properly, that you have selected the correct settings (device type and port) and try again. More Info

Oh well....

**Comment by tzikis** [comment]
hey @sean808080, can you please contact codebender's support at feedback.codebender.cc, in order to try and understand what's happening?

**Comment by ToniCorinne** [comment]
We have updated this library and pushed the changes to both Codebender and the Arduino library manager. Please reopen this if you are still having issues.
